### ISSUE TITLE
Unable to change steel sheet Z-offset for existing sheets after updating to 3.13.0 due to freeze when asked if filament is loaded. 

### ISSUE THREAD

**Issue by ddbond** [prusa3d/Prusa-Firmware#4364]
**Printer type** - [e.g. MK3S, MK3, MK2.5S, MK2.5, MK2S, MK2]
**Printer firmware version** -  [e.g. 3.8.1, 3.8.1-RC1, ...]

**MMU upgrade** - [e.g. MMU2S, MMU2, MMU1]
**MMU upgrade firmware version** - [e.g. 1.0.6, 1.0.6-RC2, ...]

**SD card or USB/Octoprint**
  Please let us know if you print via SD card or USB/Octoprint

**Describe the bug**
  
**To Reproduce**
  Please describe steps to reproduce the behavior.
  
**Expected behavior**
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by gudnimg** [comment]
This issue is fixed and will be released in 3.13.2

**Comment by ddbond** [comment]
Thanks! For the quick response!!!Dennis ***@***.*** Sep 2, 2023, at 6:09 AM, Guðni Már Gilbert ***@***.***> wrote:﻿
This issue is fixed and will be released in 3.13.2

**Comment by EeroFluge** [comment]
This issue was reported back in early August.  [BUG] FW 3.13.0 Cannot perform first layer calibration #4300 

Why is this not in the 3.13.1 build???   Still broken in 3.13.1 !

**Comment by barrem95** [comment]
> This issue is fixed and will be released in 3.13.2

When should version 3.13.2 be released?

**Comment by gudnimg** [comment]
@barrem95 it's out now https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.13.2-RC1 :)

**Comment by gudnimg** [comment]
Closing this issue as solved.
