### ISSUE TITLE
3.2.0-RC2 - Z Calibration fails

### ISSUE THREAD

**Issue by albegouws** [prusa3d/Prusa-Firmware#690]
MK3 Firmware 3.2.0-RC2
Z calibration fails with check for debris on nozzle.  Works on 3.2.0-RC1.  Not on specific point, I ran it about 5 times with two reloads of firmware, error triggers on any of the 9 points.

 Rolling back to previous version I get successful Z Calibration, back on RC2 I cannot calibrate Z.

**Comment by ghost** [comment]
Same issue.

It appears the Z motor stall guard is too sensitive, because the "bouncing" done during the Z calibration appears to be triggering a false positive collision detection.

**Comment by alientek** [comment]
No issue here.

**Comment by PavelSindler** [comment]
Thank you for reporting this issue. Yes, it seems that stall guard is too sensitive for some printers.

**Comment by dalgibbard** [comment]
Yeap this is an issue for me also. Z axis moves all the way up to the top parts, then begins to descend, makes it around 3 inches down from the top before showing calibration error.
Reverted to 3.1.3, calibration works fine.

**Comment by albegouws** [comment]
@PavelSindler changed the "#define TMC2130_SG_THRS_Z" setting to 4 - I can confirm that it runs through the calibration now.

**Comment by eowindel** [comment]
Same issue here, sometimes it passed sometimes not

**Comment by PavelSindler** [comment]
Fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/701 .

**Comment by dalgibbard** [comment]
@PavelSindler Still having the same issue here on 3.2.0 final 😢 will try compiling 3.2.0 from source with a higher stallguard value.

**Comment by dalgibbard** [comment]
set to 5, same issue - is there a limit/sensible range I can run through - and/or any values which should be considered unsafe?

**Comment by dalgibbard** [comment]
OK rather than spamming this thread, upped the value to 6, still no joy. Here's a quick video of the problem I'm seeing, to make sure its the same issue- and if not, I can raise a different ticket etc :)

https://youtu.be/Os3RgPvekaE

Works fine on FW 3.1.3! Added a touch of lithium grease and ran the Z axis up and down a handful of times, still stops when returning down for the Z calibration.

**Comment by ghost** [comment]
Darren, if it's failing with your stall guard that high, you may have a mechanical issue with your printer.

Make sure your Z smooth rods are fully seated in the Z motor mounts, and try loosening your Z trapesoid nuts and retightening them with the extruder towards the bottom.

But I'd guess your Z rods aren't parallel, one of your trapesoid nuts are bad, or one of your Z motors is bad.

**Comment by dalgibbard** [comment]
The plot thickens... I did all that, and it still didn't work with the threshold set at 6.
Flashed stock 3.2.0 back, wiped all data in a factory reset, and now the calibration works, but the print fan has failed- and self-test fails as a result... co-incidence? Wondering if there was some odd feedback on a power rail somewhere caused by a dodgy fan or something insane - but I have little knowledge of how the stall detection works :)

**Comment by dalgibbard** [comment]
OMG what the hell. So after the failed self-tests (yes, plural lol) I took the fan off, checked it for debris, reseated the connector, checked a few times more, still didn't work. Ignored the failed self-test and ran the calibration to find it worked fine. Then decided to re-run the self-test once more anyway and.... it works. I'm so baffled right now, but the important thing is it's working 🤸‍♂️ 🤷‍♂️

**Comment by dalgibbard** [comment]
And 5mins into a print, my print fan failed again... OK, i'm done here, I'll take it up with support - thanks for putting up with me! 😆

**Comment by dalgibbard** [comment]
To provide an update; looks like an intermittent fault with my PINDA probe; wiggling the cable bundle turns it off an on, so probable cable break!
